- name: Make local copy of latest NetAlertX backup
  ansible.posix.synchronize:
    mode: pull
    src: "{{ rsync_backups }}/netalertx.tar.gz"
    dest: backups
    archive: false
    checksum: true
  delegate_to: localhost

- name: Restore NetAlertX backup
  ansible.builtin.unarchive:
    src: "backups/netalertx.tar.gz"
    dest: "/var/docker/data"
    creates: "/var/docker/data/netalertx"

- name: Copy NetAlertX compose project
  ansible.builtin.copy:
    src: netalertx
    dest: /var/docker/compose
    mode: '0644'

- name: Pull NetAlertX image
  community.docker.docker_image:
    name: ghcr.io/netalertx/netalertx
    source: pull

- name: Create and start NetAlertX service
  community.docker.docker_compose_v2:
    project_src: /var/docker/compose/netalertx
    state: present

- name: Create NetAlertX maintenance cron task
  ansible.builtin.cron:
    name: NetAlertX maintenance
    hour: "4"
    minute: "55"
    user: root
    cron_file: netalertx-maint
    job: >
      docker pull ghcr.io/netalertx/netalertx &&
      cd /var/docker/compose/netalertx &&
      docker compose down &&
      tar -czf /var/docker/backups/netalertx.tar.gz -C /var/docker/data/ netalertx/ &&
      rsync -av --inplace /var/docker/backups/ "{{ rsync_backups }}/" &&
      docker compose up -d

- name: Set shell for NetAlertX maintenance cron task
  ansible.builtin.cron:
    name: "SHELL"
    env: true
    job: "/bin/bash"
    user: root
    cron_file: netalertx-maint
