# Invocation: ansible-playbook -i hosts create_vm.yml 

- name: "Setup ubuntu VM {{ inventory_hostname_short }}"
  hosts: vm_nodes
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
  - name: "Create local folders"
    file:
      path: "/tmp/{{ inventory_hostname_short }}/{{ item }}"
      state: directory
    with_items:
      - src
      - build
      - dst
    delegate_to: localhost

  - name: "Get kernel and initrd"
    get_url:
      url: "http://nl.archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/{{ item }}"
      dest: "/tmp/{{ inventory_hostname_short }}/src/"
    with_items:
      - linux
      - initrd.gz
    delegate_to: localhost

  - name: "Copy kernel and initrd"
    copy:
      src: "/tmp/{{ inventory_hostname_short }}/src/{{ item }}"
      dest: "/tmp/{{ inventory_hostname_short }}/dst/{{ item }}"
      force: yes
    with_items:
      - linux
      - initrd.gz
    delegate_to: localhost

  - name: "Copy Ubuntu preseed file"
    template:
      src: "preseed.cfg.j2"
      dest: "/tmp/{{ inventory_hostname_short }}/build/preseed.cfg"
    delegate_to: localhost

  - name: "Copy ssh public key"
    copy:
      src: "/root/.ssh/id_rsa.pub"
      dest: "/tmp/{{ inventory_hostname_short }}/build/id_rsa.pub"
      force: yes
    delegate_to: localhost

  - name: "Add to initrd.gz"
    shell: "find . | cpio -H newc -o | gzip -9 >> /tmp/{{ inventory_hostname_short }}/dst/initrd.gz"
    args:
      chdir: "/tmp/{{ inventory_hostname_short }}/build"
    delegate_to: localhost

  - name: "Copy kernel and initrd to ProxMox host"
    copy:
      src: "/tmp/{{ inventory_hostname_short }}/dst/{{ item }}"
      dest: "/tmp/{{ inventory_hostname_short }}.{{ item }}"
      force: yes
    with_items:
      - linux
      - initrd.gz
    delegate_to: pve

  - name: "Cleanup local work folders"
    file:
      path: "/tmp/{{ inventory_hostname_short }}"
      state: absent
    delegate_to: localhost

  - name: "Create {{ inventory_hostname_short }}"
    proxmox_kvm:
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_password: "{{ pve_api_password }}"
      node: pve
      name: "{{ inventory_hostname_short }}"
      vmid: "{{ vm_id }}"
      cores: "{{ vm_cores }}"
      memory: "{{ vm_mem }}"
      balloon: "{{ vm_mem }}"
      scsi: '{"scsi0":"{{ vm_disk }}:{{ vm_hd }},format=raw,discard=on"}'
      scsihw: virtio-scsi-pci
      net: '{"net0":"virtio={{ vm_mac }},bridge=vmbr0,firewall=1"}'
      ostype: l26
      args: '-kernel /tmp/{{ inventory_hostname_short }}.linux -initrd /tmp/{{ inventory_hostname_short }}.initrd.gz'
      agent: yes
      onboot: yes
    delegate_to: localhost

  - name: Wait for VM creation
    proxmox_kvm:
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_password: "{{ pve_api_password }}"
      name: "{{ inventory_hostname_short }}"
      state: current
    register: result
    until: result.msg.find("stopped") != -1
    retries: 30
    delay: 2
    delegate_to: localhost

  - name: "Start installation on VM"
    proxmox_kvm:
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_password: "{{ pve_api_password }}"
      name: "{{ inventory_hostname_short }}"
      state: 'started'
    delegate_to: localhost

  - name: Wait for VM shutdown
    proxmox_kvm:
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_password: "{{ pve_api_password }}"
      name: "{{ inventory_hostname_short }}"
      state: current
    register: result
    until: result.msg.find("stopped") != -1
    retries: 180
    delay: 10
    delegate_to: localhost

  - name: Delete custom QEMU args from VM
    proxmox_kvm:
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_password: "{{ pve_api_password }}"
      name: "{{ inventory_hostname_short }}"
      node: pve
      delete: 'args'
    delegate_to: localhost

  - name: "Delete kernel and initrd from ProxMox host"
    file:
      path: "/tmp/{{ inventory_hostname_short }}.{{ item }}"
      state: absent
    with_items:
      - linux
      - initrd.gz
    delegate_to: pve

  - name: "Start VM"
    proxmox_kvm:
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_password: "{{ pve_api_password }}"
      name: "{{ inventory_hostname_short }}"
      state: 'started'
    delegate_to: localhost
