- name: Delete old Proxmox VMs
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars.yml

  tasks:
  - name: "Stop {{ vm_name }}"
    proxmox_kvm:
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_password: "{{ pve_api_password }}"
      name: "{{ vm_name }}"
      force: yes
      state: stopped

  - name: "Delete {{ vm_name }}"
    proxmox_kvm:
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_password: "{{ pve_api_password }}"
      name: "{{ vm_name }}"
      state: absent
