# Invocation: ansible-playbook -i hosts.docker docker.yml
- name: Setup docker
  hosts: raspberrypi.fritz.box
  vars_files:
    - vars.yml
  vars:
    rsync_backups: "rsync://raspberrypi.fritz.box/docker/backups/pi"
  roles:
    - docker_base
    - portainer
    - mosquitto
    - letsencrypt
    - thelounge
    - nodered
