# Invocation: ansible-playbook -i hosts.docker docker.yml
- name: Setup docker
  hosts: raspberrypi.fritz.box

  roles:
    - docker_base
    - portainer
    - mosquitto
    - letsencrypt
    - thelounge
    - nodered
