# Invocation: ansible-playbook -i hosts k8s.yml --check

- name: Setup k8s
  hosts: k8s_all

  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      state: present
      update_cache: true

  - name: Install APT Transport HTTPS
    apt:
      name: apt-transport-https
      state: present

  - name: Install GnuPG
    apt:
      name: gnupg
      state: present

  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: add Kubernetes' APT repository
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

  - name: install kubelet
    apt:
      name: kubelet
      state: present
      update_cache: true
  - name: pin kubelet version
    dpkg_selections:
      name: kubelet
      selection: hold

  - name: install kubeadm
    apt:
      name: kubeadm
      state: present
  - name: pin kubeadm version
    dpkg_selections:
      name: kubeadm
      selection: hold

  - name: Remove swapfile from /etc/fstab
    mount:
      name: none
      fstype: swap
      state: absent
  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

- name: Setup k8s
  hosts: k8s_masters

  tasks:
  - name: install kubectl
    apt:
      name: kubectl
      state: present
  - name: pin kubectl version
    dpkg_selections:
      name: kubectl
      selection: hold

- name: setup k8s master
  hosts: k8s_masters

  tasks:
  - name: initialize the cluster
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
    args:
      chdir: $HOME
      creates: cluster_initialized.txt

  - name: create .kube directory
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755

  - name: copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes

  - name: Download calico manifest
    get_url:
      url: https://docs.projectcalico.org/manifests/calico.yaml
      dest: $HOME/calico.yaml

  - name: Update cidr
    replace:
      path: $HOME/calico.yaml
      regexp: '192.168.0.0/16'
      replace: '10.244.0.0/16'

  - name: install Pod network
    shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml >> pod_network_setup.txt
    args:
      chdir: $HOME
      creates: pod_network_setup.txt

- name: Get join command from master
  hosts: k8s_masters[0]
  gather_facts: false
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join worker
  hosts: k8s_workers
  tasks:
  - name: join cluster
    shell: "{{ hostvars[groups.k8s_masters[0]].join_command }} >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt
