# Invocation: ansible-playbook -i hosts.docker laptop.yml
- name: Build laptop server
  hosts: raspberrypi.fritz.box
  vars_files:
    - vars.yml
  vars:
    rsync_backups: "rsync://raspberrypi.fritz.box/docker/backups/pi"
  roles:
    - laptop
    - dhcp
    - fileserver
    - tribler
    - docker_base
    - portainer
    - mosquitto
    - swag
    - thelounge
    - nodered
    - influxdb
    - grafana
    - ycast
