---
version: '3'
services:
  nodered:
    image: victoriametrics/victoria-metrics
    container_name: victoriametrics
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /var/docker/data/victoriametrics/data:/victoria-metrics-data
    command:
      - "-retentionPeriod=100y"
    ports:
      - 8428:8428
    restart: unless-stopped
