---
version: '3'
services:
  nodered:
    image: netraams/ycast-docker
    container_name: ycast
    environment:
      - TZ=Europe/Amsterdam
      - YC_STATIONS=/opt/ycast/stations/stations.yml
    volumes:
      - /var/docker/data/ycast/stations:/opt/ycast/stations/
    ports:
      - 9200:80
    restart: unless-stopped
