- name: Restart DHCP server
  ansible.builtin.systemd_service:
    name: kea-dhcp4-server
    state: restarted
    enabled: true

- name: Restart DNS server
  ansible.builtin.systemd_service:
    name: unbound
    state: restarted
    enabled: true

- name: Restart Kea Control Agent
  ansible.builtin.systemd_service:
    name: kea-ctrl-agent
    state: restarted
    enabled: true
