---
version: '3'
services:
  nodered:
    image: influxdb
    container_name: influxdb
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /var/docker/data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    restart: unless-stopped
