server:
    directory: "/etc/unbound"
    username: "unbound"
    
    interface: 0.0.0.0
    interface: ::0

    do-ip6: yes
    prefer-ip6: no

    access-control: 127.0.0.0/8 allow
    access-control: 192.168.178.0/24 allow

    domain-insecure: "fritz.box"

    local-zone: "fritz.box." static


    # Fritz Box
    local-data: "fritz.box. IN A 192.168.178.1"
    local-data-ptr: "192.168.178.1 fritz.box."

    # Debian / NS1 / RaspberryPi (shared IP)
    local-data: "ns1.fritz.box. IN A 192.168.178.34"
    local-data: "debian.fritz.box. IN A 192.168.178.34"
    local-data: "raspberrypi.fritz.box. IN A 192.168.178.34"
    local-data-ptr: "192.168.178.34 debian.fritz.box."

    # CoreELEC
    local-data: "coreelec.fritz.box. IN A 192.168.178.18"
    local-data-ptr: "192.168.178.18 coreelec.fritz.box."

    # Override *.vtuner.com
    local-zone: "vtuner.com." redirect
    local-data: "vtuner.com. IN A 192.168.178.34"

forward-zone:
    name: "."
    forward-addr: 185.93.175.43
    forward-addr: 185.232.98.76
    forward-addr: 2a10:3780:2:52:185:93:175:43
    forward-addr: 2a10:3780:2:53:185:232:98:76

include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"
