- name: Install smartmontools
  apt:
    name: smartmontools
    update_cache: true

- name: Enable fs trimming
  systemd:
    name: fstrim.timer
    enabled: yes
    state: started

- name: Mount up device by UUID
  mount:
    path: /mnt/data
    src: UUID=034b76db-7b37-47f9-bdac-07091033fcbe
    fstype: ext4
    opts: errors=remount-ro
    passno: '2'
    state: present

- name: Install desktop
  apt:
    name: xfce4

- name: Enable remote desktop
  apt:
    name: xrdp

- name: Enable browsing network shares
  apt:
    name: gvfs-backends

- name: Install bc
  apt:
    name: bc

- name: "Copy HD stats script"
  copy:
    src: hd-stats.sh
    dest: /root
    owner: root
    group: root
    mode: 0755

- name: Create HD stats cron task
  cron:
    name: HD stats
    minute: "0"
    hour: "6"
    user: root
    job: /root/hd-stats.sh
    cron_file: hd-stats
