- name: Install resolvconf
  apt:
    name: resolvconf
    state: present

- name: Copy static IP configuration template
  template:
    src: "{{ item }}.j2"
    dest: /etc/network/interfaces.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - static

- name: Install DNS server
  apt:
    name: bind9
    state: present
    update_cache: true

- name: Install DHCP server
  apt:
    name: isc-dhcp-server
    state: present

- name: Copy DHCP configuration templates
  template:
    src: "{{ item }}.j2"
    dest: /etc/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - dhcp/dhcpd.conf
    - default/isc-dhcp-server
  register: dhcp_conf

- name: Copy DNS configuration files
  copy:
    src: "{{ item }}"
    dest: /etc/bind/{{ item }}
    owner: root
    group: bind
    mode: 0644
  with_items:
    - named.conf.options
    - named.conf.local
  register: bind9_conf

- name: Copy DNS zone files
  copy:
    src: "{{ item }}"
    dest: /etc/bind/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - db.fritz.box
    - db.192.168.178
    - rpz.ycast
  register: bind9_zones

- name: Restart DHCP server
  service:
    name: isc-dhcp-server
    state: restarted
  when: dhcp_conf.changed

- name: Restart DNS server
  service:
    name: bind9
    state: restarted
  when: bind9_conf.changed or bind9_zones.changed
