- name: Install resolvconf
  apt:
    name: resolvconf
    state: present

- name: Copy static IP configuration template
  template:
    src: "{{ item }}.j2"
    dest: /etc/network/interfaces.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - static

- name: Install DNS server
  apt:
    name: unbound
    state: present
    update_cache: true

- name: Install DHCP server
  apt:
    name: isc-dhcp-server
    state: present

- name: Disable unbound 'helper'
  service:
    name: unbound-resolvconf
    state: stopped
    enabled: false

- name: Copy DHCP configuration templates
  template:
    src: "{{ item }}.j2"
    dest: /etc/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - dhcp/dhcpd.conf
    - default/isc-dhcp-server
  register: dhcp_conf

- name: Copy DNS configuration files
  copy:
    src: "{{ item }}"
    dest: /etc/unbound/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - unbound.conf
  register: unbound_conf

- name: Restart DHCP server
  service:
    name: isc-dhcp-server
    state: restarted
  when: dhcp_conf.changed

- name: Restart DNS server
  service:
    name: unbound
    state: restarted
  when: unbound_conf.changed
