- name: Install resolvconf
  apt:
    name: resolvconf
    state: present

- name: Copy static IP configuration
  copy:
    src: "{{ item }}"
    dest: /etc/network/interfaces.d/{{ item }}
    owner: root
    group: bind
    mode: 0644
  with_items:
    - static

- name: Install DNS server
  apt:
    name: bind9
    state: present
    update_cache: true

# - name: Install DHCP server
#   apt:
#     name: isc-dhcp-server
#     state: present


- name: Copy DNS configuration files
  copy:
    src: "{{ item }}"
    dest: /etc/bind/{{ item }}
    owner: root
    group: bind
    mode: 0644
  with_items:
    - named.conf.options
    - named.conf.local
  register: bind9_conf

- name: Copy DNS zone files
  copy:
    src: "{{ item }}"
    dest: /etc/bind/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - db.fritz.box
    - db.192.168.178
    - rpz.ycast
  register: bind9_zones

- name: Restart DNS server
  service:
    name: bind9
    state: restarted
  when: bind9_conf.changed or bind9_zones.changed
