FROM nodered/node-red

RUN npm install node-red-contrib-moment
RUN npm install node-red-dashboard
RUN npm install node-red-node-email
RUN npm install node-red-contrib-credentials
RUN npm install node-red-contrib-sun-position
