- name: Make local copy of latest portainer backup
  synchronize:
    mode: pull
    src: "{{ rsync_backups }}/portainer.tar.gz"
    dest: backups
    archive: false
    checksum: true
  delegate_to: localhost

- name: "Restore portainer backup"
  unarchive:
    src: "backups/portainer.tar.gz"
    creates: "/var/docker/data/portainer"
    dest: "/var/docker/data"

- name: "Copy Portainer compose project"
  copy:
    src: portainer
    dest: /var/docker/compose

- name: Pull Portainer image
  docker_image:
    name: portainer/portainer
    source: pull

- name: "Create and start Portainer service"
  docker_compose:
    project_src: /var/docker/compose/portainer

- name: Create Portainer maintenance cron task
  cron:
    name: Portainer maintenance
    minute: "20"
    hour: "4"
    user: root
    job: >
      docker pull portainer/portainer &&
      pushd /var/docker/compose/portainer &&
      /usr/local/bin/docker-compose down &&
      tar -czf /var/docker/backups/portainer.tar.gz -C /var/docker/data/ portainer/ &&
      rsync -av --inplace /var/docker/backups/ "{{ rsync_backups }}/" &&
      /usr/local/bin/docker-compose up -d
    cron_file: portainer-maint

- name: "Set shell for Portainer maintenance cron task"
  cron:
    name: "SHELL"
    env: yes
    job: "/usr/bin/bash"
    user: root
    cron_file: portainer-maint
