- name: "Make local copy of latest The Lounge backup"
  synchronize:
    mode: pull
    src: "{{ rsync_backups }}/thelounge.tar.gz"
    dest: backups
    archive: false
    checksum: true
  delegate_to: localhost

- name: "Restore The Lounge backup"
  unarchive:
    src: "backups/thelounge.tar.gz"
    creates: "/var/docker/data/thelounge"
    dest: "/var/docker/data"

- name: "Copy The Lounge compose project"
  copy:
    src: thelounge
    dest: /var/docker/compose

- name: "Pull The Lounge image"
  docker_image:
    name: thelounge/thelounge
    source: pull

- name: "Create and start The Lounge service"
  docker_compose:
    project_src: /var/docker/compose/thelounge

- name: "Create The Lounge maintenance cron task"
  cron:
    name: "The Lounge maintenance"
    minute: "50"
    hour: "4"
    day: "1"
    user: root
    job: >
      docker pull thelounge/thelounge &&
      pushd /var/docker/compose/thelounge &&
      /usr/bin/docker-compose down &&
      tar -czf /var/docker/backups/thelounge.tar.gz -C /var/docker/data/ thelounge/ &&
      rsync -av --inplace /var/docker/backups/ "{{ rsync_backups }}/" &&
      /usr/bin/docker-compose up -d
    cron_file: thelounge-maint

- name: "Set shell for The Lounge maintenance cron task"
  cron:
    name: "SHELL"
    env: yes
    job: "/usr/bin/bash"
    user: root
    cron_file: thelounge-maint
