- name: "Copy Mosquitto compose project"
  copy:
    src: mosquitto
    dest: /var/docker/compose

- name: "Pull Mosquitto image"
  docker_image:
    name: eclipse-mosquitto
    source: pull

- name: "Create and start Mosquitto service"
  docker_compose:
    project_src: /var/docker/compose/mosquitto

- name: Create Mosquitto maintenance cron task
  cron:
    name: Mosquitto maintenance
    minute: "30"
    hour: "4"
    user: root
    job: >
      docker pull eclipse-mosquitto ;
      pushd /var/docker/compose/mosquitto ;
      /usr/local/bin/docker-compose down ;
      /usr/local/bin/docker-compose up -d
    cron_file: mosquitto-maint
