# Install docker/docker compose, and create some useful folders
- name: Install Docker
  apt:
    name: docker.io
    update_cache: true

- name: Install Docker Compose
  apt:
    name: docker-compose

- name: Install python
  apt:
    name: python3

- name: Install pip
  apt:
    name: python3-pip

- name: Install Docker Module for Python
  apt:
    name: python3-docker

- name: Install Docker Compose Module for Python
  apt:
    name: python3-compose

- name: "Create folder to keep Docker bind mounts at"
  file:
    path: "/var/docker/data"
    state: directory

- name: "Create folder to keep Docker compose files at"
  file:
    path: "/var/docker/compose"
    state: directory

- name: "Create folder to keep Docker backups at"
  file:
    path: "/var/docker/backups"
    state: directory
