---
version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - data:/mosquitto/data
      - log:/mosquitto/log
      - /var/docker/data/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    restart: unless-stopped
volumes:
  data:
  log:
