- name: "Make local copy of latest Let's Encrypt backup"
  synchronize:
    mode: pull
    src: "{{ rsync_backups }}/letsencrypt.tar.gz"
    dest: backups
    archive: false
    checksum: true
  delegate_to: localhost

- name: "Restore Let's Encrypt backup"
  unarchive:
    src: "backups/letsencrypt.tar.gz"
    creates: "/var/docker/data/letsencrypt"
    dest: "/var/docker/data"

- name: "Copy Let's Encrypt compose project"
  copy:
    src: letsencrypt
    dest: /var/docker/compose

- name: "Copy Let's Encrypt compose project file"
  template:
    src: letsencrypt/docker-compose.yml.j2
    dest: /var/docker/compose/letsencrypt/docker-compose.yml

- name: "Pull Let's Encrypt image"
  docker_image:
    name: linuxserver/letsencrypt
    source: pull

- name: "Create and start Let's Encrypt service"
  docker_compose:
    project_src: /var/docker/compose/letsencrypt

- name: "Create Let's Encrypt maintenance cron task"
  cron:
    name: "Let's Encrypt maintenance"
    minute: "40"
    hour: "4"
    user: root
    job: >
      docker pull linuxserver/letsencrypt &&
      pushd /var/docker/compose/letsencrypt &&
      /usr/local/bin/docker-compose down &&
      tar -czf /var/docker/backups/letsencrypt.tar.gz -C /var/docker/data/ letsencrypt/ &&
      rsync -av --inplace /var/docker/backups/ "{{ rsync_backups }}/" &&
      /usr/local/bin/docker-compose up -d
    cron_file: letsencrypt-maint

- name: "Set shell for Let's Encrypt maintenance cron task"
  cron:
    name: "SHELL"
    env: yes
    job: "/usr/bin/bash"
    user: root
    cron_file: letsencrypt-maint
